package hiperus

type ReleaseCode byte

var releaseCodes = []string{
	"0",
	"Unallocated (unassigned) number",
	"No route to specific transit network",
	"No route to destination",
	"Send special info tone",
	"Misdialed trunk prefix",
	"Channel unacceptable",
	"Call awarded and being delivered in established channel",
	"Preemption",
	"Preemption - circuit reserved for reuse",
	"10",
	"11",
	"12",
	"13",
	"14",
	"15",
	"Normal call clearing",
	"User busy",
	"No user responding",
	"No answer from user (user alerted)",
	"Subscriber absent",
	"Call rejected",
	"Number changed",
	"Redirect to new destination (unallocated destination number ANSI)",
	"Unknown business group (ANSI)",
	"Exchange routing error (ANSI)",
	"Non-selected user clearing",
	"Destination out of order",
	"Invalid number format",
	"Facility rejected",
	"Response to STATUS ENQUIRY",
	"Normal, unspecified",
	"32",
	"33",
	"No circuit/channel available",
	"35",
	"36",
	"37",
	"Network out of order",
	"Permanent frame mode connection out of service",
	"Permanent frame mode connection operational",
	"Temporary failure",
	"Switching equipment congestion",
	"Access information discarded",
	"Requested channel/circuit not available",
	"Preemption (ANSI)",
	"Precedence call blocked",
	"Resources unavailable, unspecified",
	"48",
	"Quality of service unavailable",
	"Requested facility not subscribed",
	"Call type incompatible with service request (ANSI)",
	"52",
	"Outgoing calls barred within CUG",
	"Call blocked due to group restrictions (ANSI)",
	"Incoming calls barred within CUG",
	"56",
	"Bearer capability not authorized",
	"Bearer capability not presently available",
	"59",
	"60",
	"61",
	"Inconsistency in designed outg. access inf. and subscr. class",
	"Service or option not available, unspecified",
	"64",
	"Bearer capability not implemented",
	"Channel type not implemented",
	"67",
	"68",
	"Requested facility not implemented",
	"Only restricted digital bearer cap. is available",
	"71",
	"72",
	"73",
	"74",
	"75",
	"76",
	"77",
	"78",
	"Service or option not implemented, unspecified",
	"80",
	"Invalid call reference value",
	"Identified channel does not exist",
	"A suspended call exists, but this call identity does not",
	"Call identity in use",
	"No call suspended",
	"Call having the requested call identity has been cleared",
	"User not member of CUG",
	"Incompatible destination",
	"89",
	"Non-existing CUG",
	"Invalid transit network selection",
	"92",
	"93",
	"94",
	"Invalid message, unspecified",
	"Mandatory information element is missing",
	"Message type non-existing or not implemented",
	"Message incompatible with call state or mesg type non-existent or not implemented",
	"Information element non-existent or not implemented",
	"Invalid information element contents",
	"Message not compatible with call state",
	"Recovery on timer expiry",
	"Parameter non-existent or not implemented - passed on",
	"104",
	"105",
	"106",
	"107",
	"108",
	"109",
	"Message with unrecognized parameter discarded",
	"Protocol error, unspecified",
	"112",
	"113",
	"114",
	"115",
	"116",
	"117",
	"118",
	"119",
	"120",
	"121",
	"122",
	"123",
	"124",
	"125",
	"126",
	"Interworking, unspecified",
}

func (rc ReleaseCode) String() string {
	if rc > 127 {
		return "unknown"
	}
	return releaseCodes[rc]
}
